### ISSUE TITLE
ut-server not running at all after installation and asu.sh verifies 

### ISSUE THREAD

**Issue by elsheepo** [abfackeln/ut#1]
I have extracted ut-server-436.tar.gz, extracted asu-0.6.tar.gz to the ut-server/ directory, ran asu.sh, installed ucc.init script, but when I run it, I get `Starting Unreal Tournament' ucc.init` yet, nothing works, webadmin cannot connect, server is not shown in UTs find LAN games menu, and when checking for process using top/htop/ps it is not shown. please help me, Ive been stuck for days.

**Comment by abfackeln** [comment]
hi.  i hadn't run this for years but when i tried recently, it failed with the same symptoms.  i am now running a Debian "Jessie" system, which is pretty old but not old enough, apparently -- it turns out that the old binary format is not supported anymore.  at least not by default.  i had to install the old libc6 library to get it to work:
`sudo apt-get install libc6-i386`

**Comment by elsheepo** [comment]
indeed, i386 architecture is required.  I've got a server up and running with UTPureRC7G on my home server using this: [ut99server](https://linuxgsm.com/lgsm/ut99server/ "ut99server").  You can check it out if you want, the address is `unreal://beatzz.co:7777`, although for some reason it wont show up in the _Unreal Tournament Server Browser_ .  I've been fussing with that all day.  On [UnrealAdmin](http://www.unrealadmin.org/forums "UnrealAdmin Fourms") it seems to be a reoccurring issue.

**Comment by abfackeln** [comment]
getting a new server to show up in the server browser can be finicky, even if everything is set up correctly...  i don't know of a sure way to fix that.  i used to manually find my server (by entering the IP) then play a few games, and after that my server will usually show up in the browser.  not exactly a science but i don't have a better answer for that...  :/
