### ISSUE TITLE
I have fixes to allow this to work under Ubuntu DiscoDingo and Perl v5.28.1

### ISSUE THREAD

**Issue by trbaldwin60** [abfackeln/ut#2]
Please grant me access to push a new branch with the fixes so you can have them.

**Comment by abfackeln** [comment]
Hi, @trbaldwin60, sorry for the late response.  Plz fork the project, commit your changes, then make a pull request.  I'd like to see it.  Thx.

**Comment by acolchagoff** [comment]
I need these fixes as well, any update here?

**Comment by abfackeln** [comment]
@denodster i'm guessing this addresses the issue that @trbaldwin60 mentioned.  i have approved the merge.  tell me if it works for you.

**Comment by abfackeln** [comment]
i will interpret the silence to mean it works.  :)
